name: selenium-tests

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install selenium webdriver-manager pytest pytest-html

      - name: Run pytest
        run: pytest -q tests --html=report.html --self-contained-html

      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: selenium-report
          path: |
            report.html
            artifacts/**
